- CHANGELOG.md
- deploy/newrelic-infra-unprivileged.yaml
- deploy/newrelic-infra.yaml
- e2e/charts/newrelic-infrastructure-k8s-e2e/templates/cluster-role.yaml
- e2e/charts/newrelic-infrastructure-k8s-e2e/templates/daemonset.yaml
- src/controlplane/client/discovery.go
- src/controlplane/components.go
This adds support for Kubernetes v1.17.
Basically now the metrics from the API server are being queried over the secure port (443) by default. If the query to the secure port fails, we automatically and transparently fallback to the insecure one.
> Add support for Kubernetes v1.17

- Jenkinsfile
- e2e/schema/deployment.json
- src/metric/definition.go
This PR will add 2 new E2E clusters: 1.17.9 & 1.18.x
> Add Kubernetes 1.17.9 E2E cluster

- CHANGELOG.md
- Dockerfile
- deploy/newrelic-infra-unprivileged.yaml
- deploy/newrelic-infra.yaml
- src/kubernetes.go
I see one of the commit messages is wrong (references 1.16.0 instead of 1.26.0). It'll be fixed when squash merging the PR.
> Release 1.26.0

- CHANGELOG.md
- Dockerfile
- deploy/newrelic-infra-unprivileged.yaml
- deploy/newrelic-infra.yaml
- src/kubernetes.go
Updated to latest version of bundle agent,  [v1.5.0](https://github.com/newrelic/infrastructure-bundle/releases/tag/1.5.0)
> chore: Updated infrastructure-bundle to v1.5.0

- Dockerfile
Reopened from #21 using a local branch to get the CI running 
This:
- reaps orphaned zombie process attached to PID 1
- correctly forwards signals to CMD process
Base infrastructure agent image uses it: https://hub.docker.com/layers/newrelic/infrastructure/latest/images/sha256-509908017550b739445db36cb7172b267d51fcc21ab28fc3b5532b4868191585?context=explore
Read for more details: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
> Use Tini entrypoint

- src/kubelet/metric/pods.go
in case a pod is in a crash loop we were not getting the restart count
> fix: add restart count metric to terminated pods

- src/kubelet/metric/pods.go
in case a pod is in a crash loop we were not getting the restart count.
> fix: add restart count metric to waiting pods

- CHANGELOG.md
- src/ksm/client/discovery.go
- src/ksm/client/discovery_test.go
Kubernetes returns "None" as the clusterIP of headless Services.
This was causing the KSM discovery to think the DNS based discovery was successful, when in fact the returned IP is `"None"` and cannot be reached.
With this patch if the returned clusterIP is `"None"` it will be automatically skipped. And if it's the only address found, the DNS discovery will fail.
> Correctly fail DNS discovery for KSM behind headless services

- CHANGELOG.md
- Dockerfile
- deploy/newrelic-infra-unprivileged.yaml
- deploy/newrelic-infra.yaml
- src/kubernetes.go
Bumping base image to update all the bundled integrations.
More info regarding all the integration upgraded can be found in the [release notes of the base image](https://github.com/newrelic/infrastructure-bundle/releases/tag/2.0.0).
> feat(baseImage): updating base image

- .github/workflows/helm.yml
Job analogous to [nri-prometheus](https://github.com/newrelic/nri-prometheus/blob/main/.github/workflows/helm.yml)', which creates a PR bumping the `appVersion` of the helm chart associated to this repo in [helm-charts](https://github.com/newrelic/helm-charts).
> bump helm chart on release

- src/metric/definition.go
Previously, the `LoadBalancerIP` field was retrieved from `kube_service_info.load_balancer_ip`. This value, however, seems to be blank for the current ksm version.
This PR changes it to be retrieved from `kube_service_status_load_balancer_ingress.ip`, which seems to be working with the current version.
Temporary images images for testing are available:
- `roobre/infrastructure-k8s:load-balancer`
- `roobre/infrastructure-k8s:load-balancer-unprivileged`
---
Fixes #74
> Retrieve load balancer IP from kube_service_status_load_balancer_ingress

- src/featureflag/static_pod_status.go
- src/featureflag/static_pod_status_test.go
We found that on GKE the minor version of the k8s server contained a symbol and that was causing that `StaticPodsStatus(v *version.Info)` failed to detect if the version was grater than 1.14. This caused static pods not being appropriately synced.
json sample of the version input:
```json
Server Version: version.Info{Major: "1", Minor: "18+",
```
This PR adds a regex to strip any character from the version and take the first left match. 
Note: There are some packages to compare semantic version but in this case the string does not match a [semantic version regex](https://regex101.com/r/Ly7O1x/3/) so is useless for this particular case.
> fix: filter symbol from server version

- .github/workflows/helm.yml
Previously, the `curl` command in this job used `$variables` enclosed in `'single quoted strings'`, which prevented their expansion. This PR fixes that.
> fix upgrade-chart dispatch

- e2e/charts/newrelic-infrastructure-k8s-e2e/templates/daemonset.yaml
- e2e/cmd/e2e.go
The current E2E implementation is selecting all pods available with the infra label, however this could lead to select `terminating` pods of previous release. This causes annoying false errors in tests complaining about containers not found.
> Selecting only pods we are interested about in E2E

- Dockerfile
Those build args were not being used anywhere in the pipeline. If they were, versions would be defined in two different places, hurting maintainability.
Moreover, by having a "standard" `FROM` line, we can make use of Dependabot's bumping feature for the base image.
> dockerfile: hardcode IMAGE_NAME and IMAGE_TAG

- .github/workflows/release.yml
Otherwise, the image will not be loaded to the host from the multiarch builder and trivy will not be able to find it. This should be fast since the image is already in the builder cache.
> ci/trivy: re-run build step with --load

- Dockerfile
https://github.com/newrelic/infrastructure-bundle/releases/tag/2.6.0
> dockerfile: bump base image to infrastructure-bundle:2.6.0

- .github/workflows/nightly.yml
- Dockerfile
This PR adds new GitHub Actions workflow, which will build and push
integration Docker images daily, so one can use those images in bleeding
edge environments to spot any potential issues.
Based on https://github.com/newrelic/infrastructure-bundle/pull/67
Closes #125
> Add nightly builds

- e2e/charts/newrelic-infrastructure-k8s-e2e/values.yaml
- e2e/jsonschema/match.go
- e2e/schema/node-no-network.json
- e2e/schema/node.json
- src/metric/definition.go
- src/metric/definition_test.go
- src/prometheus/definition.go
- src/prometheus/definition_test.go
_Includes commits from #148_. Proper diff to look at is here: https://github.com/newrelic/nri-kubernetes/compare/invidian/improvements...invidian/add-node-status-metrics
Draft as the following things are missing:
> Add node status conditions metrics

- cmd/kubernetes-discovery/main.go
- e2e/cmd/e2e.go
- src/client/client.go
- src/client/client_mock.go
- src/ksm/client/discovery.go
- src/ksm/client/discovery_test.go
- src/ksm/client/distributed_pod_label_discovery.go
- src/ksm/client/pod_label_discovery.go
> General improvements

- cmd/kubernetes-static/main.go
The former makes stdout not json-conformant and cannot be piped to jq, which annoys me to ontological levels
> kubernetes-static: log with logrus rather than fmt.Println

- CHANGELOG.md
Update changelog with out-of-order releases 2.7.1 and 2.8.1.
> changelog: sync with out-of-order releases

- src/client/cached.go
- src/kubernetes.go
It has been removed in next SDK version, so not using it will make
migration easier.
Signed-off-by: Mateusz Gozdek <mgozdek@microsoft.com>
Follow up to #227, found some remaining changes while attempting to rebase #160.
Draft as there might be more found.
> src/client: don't use WithError() logger method

- .github/workflows/nightly.yml
`infrastructure-bundle` image runs at 3AM, which does not leave enough time for this nightly to be built on top of the `infratructure-bundle` nightly of the same day.
https://github.com/newrelic/infrastructure-bundle/blob/846e97b3e0d3817aa37d7a0f1ca1eb30c504ad6c/.github/workflows/nightly.yml#L4
> ci: run nightly job at 4AM

- internal/testutil/assert.go
- src/ksm/ksm_test.go
This ~tentative~ PR introduces `ExcludeFunc`, a function that can be user-defined and returns true if a metric should be allowed to be missing from the test.
This can be used to handle complex scenarios, like excluding/including a metric only if an entity matches a pattern. For example, with the previously known problem of not failing for container memory limit metrics one could do:
```go
asserter := testutil.NewAsserter().
Using(metric.KubeletSpecs).
Excluding(func(group string, spec *definition.Spec, ent *integration.Entity) bool {
return group == "container" && spec.Name == "memoryLimitBytes" && ent.Metadata.Name != "container-with-limits"  
})
```
This way we will exclude the `memoryLimitBytes` metric for `group == "container"` if the entity is not named `container-with-limits`, which …
> Allow testutil.Asserter to use user-defined excludeFuncs

- internal/config/config.go
It was not possible to set verbose as Env Var since we needed to set in in Viper first
Adding networkRouteFile as well
> Fix verbose setting a default

- src/metric/definition.go
During the development of #282, we noticed the `loadBalancerIP` metric of the `K8sServiceSample` and `namespace` from `K8sHpaSample` were not being populated.
For the first case, this was being caused by attempting to get the `ip` label from the `kube_service_status_load_balancer_ingress` metric (from KSM). This metric will not be present if an ingress is not involved with the loadBalancer, so the label was not retrieved.
In the second case the root cause was very similar, retrieving the `namespace` label from the `kube_hpa_status_condition` metric which will not always be present.
This PR simply changes the source metric for those two attributes.
> fix loadBalancerIP for services and namespaces for HPA

- src/controlplane/discoverer/discoverer.go
- src/controlplane/discoverer/discoverer_test.go
- src/controlplane/scraper.go
Moves pod discover logic to Discoverer, and add some corner cases testing.
Fixes #241
> Control plane Discoverer

- cmd/kubernetes-static/main.go
- internal/testutil/k8s.go
- internal/testutil/testutil.go
- src/controlplane/controlplane_test.go
- src/ksm/ksm_test.go
- src/kubelet/kubelet_test.go
Built on top of #281
Fake K8s object retrievers from the `testutil` package have been slightly modified to return objects by version, rather than sharing the same for all of them. This aligns better with the testdata tree. KSM and Kubelet scraper tests have been migrated accordingly.
Finally, during these tests, some bugs have been fixed and squashed, related to a missing `namespaceName` metric in HPA sample, and missing `LoadBalancerIP` in ServiceSample.
> Update tests to new testdata format introduced in #281

- Makefile
- cmd/kubernetes-static/main.go
- cmd/nri-kubernetes/main.go
- e2e/e2e-values.yml
- internal/config/config.go
- internal/config/testdata/config.yml
- internal/config/testdata/config_with_unexpected_fields.yml
- src/kubelet/scraper.go
- src/prometheus/query_test.go
Fix https://github.com/newrelic/nri-kubernetes/issues/284 -> changing the scope for network Route file in config
Fix https://github.com/newrelic/nri-kubernetes/issues/276 -> automatically inject version
Cleaning us kubelet creation for CP (it used to be used for CP as well before informers)
Cleaning as well unused functions and parameters.
All changes included in one PR but divided per commit
> Fixing small issues

- internal/testutil/assert.go
- internal/testutil/asserter/assert.go
- internal/testutil/asserter/exclude/exclude.go
- src/controlplane/controlplane_test.go
- src/ksm/ksm_test.go
- src/kubelet/kubelet_test.go
This PR makes the `ExcludeFunc`s included with the `asserter` smaller and more composable. This is done by means of a very simple ExcludeFunc:
```go
// Exclude returns an ExcludeFunc that returns true if all the supplied ExcludeFuncs return true.
// Input ExcludeFuncs are evaluated in order, so this function makes easy to compose exclusion rules.
func Exclude(funcs ...ExcludeFunc) ExcludeFunc {
```
Which allow to chain other excludeFuncs:
```go
exclude.Exclude(
// for pods...
exclude.Groups("pod"),
// that are waiting...
func(_ string, _ *definition.Spec, ent *integration.Entity) bool {
return asserter.EntityMetricIs(ent, "status", "waiting")
},
// exclude metrics defined in this `metricsToExcludeForPendingPods`
exclude.Metrics(metricsToExcludeForPendingPods...),
),
```
Achieving complex …
> testutil/asserter: improve composability of exclude functions

- cmd/kubernetes-static/main.go
- src/client/interfaces.go
- src/controlplane/client/client.go
- src/controlplane/client/client_test.go
- src/controlplane/grouper/group.go
- src/controlplane/scraper.go
- src/ksm/ksm_test.go
- src/kubelet/kubelet_test.go
- src/prometheus/query.go
- src/prometheus/query_test.go
The objective of this PR is making the control plane scraper more standard
Notice that it does not satisfy `prometheus.MetricFamiliesGetFunc`, since the url path is injected by the connector
> Refactor controlPlane getter.

- cmd/kubernetes-static/main.go
- cmd/nri-kubernetes/main.go
- src/definition/populate_test.go
- src/scrape/scrape_job_test.go
Since the integration is now long-running, it no longer needs to persist metrics for delta calculations or other tasks.
This removes the need to mount emptyDir volumes on `/tmp` for the integration container.
Open questions:
- ~Is `InMemoryStore` production ready, or meant for testing purposes only?~
- Will it behave properly in the long term, or will it leak resources?
> main: use in-memory store for integration

- internal/config/config.go
- internal/discovery/endpoints_discoverer.go
- internal/discovery/endpoints_discoverer_test.go
- internal/discovery/endpoints_discoverer_timeout_test.go
- src/ksm/scraper.go
A new `EndpointsDiscoverer` implementation, `EndpointsDiscovererWithTimeout` has been added. EndpointsDiscovererWithTimeout wraps another EndpointsDiscoverer adding a simple retry logic on top.
Main motivation for this change is to have the KSM pod no crash if KSM has not been deployed, although it can also be useful to make it more tolerant for other situations like KSM being migrated.
> ksm: wait for some time for endpoints to appear before erroring

- Dockerfile
`curl` and `dig` are basic troubleshooting tools that allows customers and developers to debug errors connecting to several of the APIs the integration needs to work.
In unprivileged mode, or with `readOnlyFilesystem: true` it will be impossible for users to install these tools after the image has been deployed in the cluster, hence the need for having them beforehand.
> Dockerfile: add curl and bind-tools

- cmd/nri-kubernetes/main.go
- internal/storer/storer.go
- internal/storer/storer_test.go
The implementation is almost the same of the SDK one. The main difference is the goroutine cleaning each interval all entries too old
> feat(leak): custom cache cleaning itself periodically

- .github/dependabot.yml
Since external PRs do not have access to secrets they fail.
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#labels
> Update dependabot.yml to skip e2e

- cmd/nri-kubernetes/main.go
- internal/config/config.go
- src/scrape/scrape_job.go
So-called recoverable "errors" are expected to happen, as it is nearly impossible for a cluster to have all possible metrics available.
This PR changes log level of these errors to `Trace`.
> scrape/job: log recoverable errors as Trace

- cmd/nri-kubernetes/main.go
- internal/config/config.go
- src/integration/wrapper.go
When debugging, it is often helpful to manually inspect the payload of the integration. This PR adds a config flag that will cause the integration to use stdout as a sink, rather than the infra agent.
This will also skip the agent pod readiness check.
> integration: allow to specify a custom sink

- Dockerfile
Since the integration is now a standalone binary, there is no real reason for the binary to be placed in such a complicated path.
As for the chmod, `ADD --chmod` is supported only when using BuildKit. Since we already need to perform a `RUN mv`, using a `chmod` command instead removes the BuildKit requirement while not adding any extra layer to he image.
> Dockerfile: simplify binary path, ensure 755 permissions

- src/ksm/ksm_test.go
- src/metric/definition.go
Fix https://github.com/newrelic/nri-kubernetes/issues/244
Notice that the pod metrics are fetched **only** for pending pods thanks to `IDGenerator: prometheus.FromLabelsValueEntityIDGeneratorForPendingPods(),`
A different approach would be to completely remove the fetch function and to hardcode that to `false`, let me know if you have any preference.  
I removed along the way also startTime since it was meaningless for pending pods
> fix(pendingPods): some metrics are missing from KSM

- .github/workflows/release-integration.yml
A small bug was introduced in the ci/cd pipeline, it affect for sure also [nri-metadata-injection](https://github.com/newrelic/k8s-metadata-injection/blob/805f1c8993ee497dc57fb6621b34f594fdf218cf/.github/workflows/release-integration.yml#L76) and [metrics-adapter](https://github.com/newrelic/newrelic-k8s-metrics-adapter/blob/24fd202c0b0699ebf2bc326e0df20876f3f24885/.github/workflows/release-integration.yml#L78)
> fix(ci/cd): extra char in pipline command

- .github/workflows/e2e.yaml
- .github/workflows/push_pr.yaml
- .github/workflows/release-chart.yml
This allows emptying `helm-charts` repository from legacy charts.
The helm chart for `v2` is waiting in the PR #415
> Release charts also from v2 branch

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/templates/_helpers_compatibility.tpl
- charts/newrelic-infrastructure/templates/controlplane/_agent-config_helper.tpl
- charts/newrelic-infrastructure/templates/ksm/_agent-config_helper.tpl
- charts/newrelic-infrastructure/templates/kubelet/_agent-config_helper.tpl
- charts/newrelic-infrastructure/tests/configmap_cp_agent_test.yaml
- charts/newrelic-infrastructure/tests/configmap_ksm_agent_test.yaml
- charts/newrelic-infrastructure/tests/configmap_kubelet_agent_test.yaml
- charts/newrelic-infrastructure/values.yaml
With this change, users should be able to add their own custom environment variables and files so they can use them in their custom configurations.
> [chart] Passthrough environment variables to integrations

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/templates/kubelet/integrations-configmap.yaml
- charts/newrelic-infrastructure/values.yaml
The functionality to self-monitor pixie was added while `v2` was in beta on the `v2` chart and we did not port that functionality to the `v3` chart.
This should add that lost feature again.
> [chart] Add pixie self monitoring

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/templates/controlplane/_agent-config_helper.tpl
- charts/newrelic-infrastructure/templates/ksm/_agent-config_helper.tpl
- charts/newrelic-infrastructure/templates/kubelet/_agent-config_helper.tpl
- charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml
- charts/newrelic-infrastructure/tests/configmap_cp_agent_test.yaml
- charts/newrelic-infrastructure/tests/configmap_ksm_agent_test.yaml
- charts/newrelic-infrastructure/tests/configmap_kubelet_agent_test.yaml
- charts/newrelic-infrastructure/tests/unprivileged_override_host_root_test.yaml
This is needed as env vars take precedence over config values. We were setting this as a config value while unaware that the image we ship set these env vars in the Dockerfile.
> chart: set overide_host_root as an env var rather than a config entry

- .github/workflows/e2e.yaml
- .github/workflows/nightlyAndMainImage.yml
- .github/workflows/push_pr.yaml
- .github/workflows/release-integration.yml
Go version in `go.mod` was updated in https://github.com/newrelic/nri-kubernetes/pull/403, but build pipelines did not reflect this change before this PR.
For traceability these changes were made with
```
find .github -type f  | xargs sed -i 's/1\.17/1.18/'
```
And then manually editing `e2e.yaml` to undo the wrong replacement on k8s 1.17.x.
> go: upgrade to 1.18

- cmd/nri-kubernetes/main.go
- cmd/nri-kubernetes/main_test.go
> Move filter creation to KSM & Kubelet methods

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/values.yaml
The readme was outdated and a bit confusing, now the "yaml" is added automatically:
```
{{- if .Values.integrations -}}
{{- range $k, $v := .Values.integrations -}}
{{- $k | trimSuffix ".yaml" | trimSuffix ".yml" | nindent 2 -}}.yaml: |-
{{- tpl ($v | toYaml) $ | nindent 4 -}}
{{- end }}
{{- end }}
```
Also the example key did not specify ".yaml" -> nri-redis-sampleapp
> feat(readme): the yaml suffix is not needed

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/templates/clusterrole.yaml
- charts/newrelic-infrastructure/values.yaml
- Update chart to the latest version of nri-kubernetes with namespace filtering
- Update clusterrole to allow ns watch and list
> Update chart to the latest version of nri-kubernetes with namespace filtering

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/templates/controlplane/daemonset.yaml
- charts/newrelic-infrastructure/templates/ksm/deployment.yaml
- charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml
- charts/newrelic-infrastructure/tests/disable_dns_test.yaml
- charts/newrelic-infrastructure/tests/hostname_override_test.yaml
Fix https://github.com/newrelic/nri-kubernetes/issues/435
After some discussion, to avoid the fullHostname to be changing depending on the service bounded to the same nodeIP, the only path forward is to overwrite that with the node name.
- In cloud environments the GUID is computed thanks to ID coming from the different vendors (es: ARN). 
- On premise an unique identifier is not available and this change increases the chances of collisions (but [different parameters](https://github.com/newrelic/infrastructure-agent/blob/c19c3bad1913255fa1438775eb10b77ecb5f09c8/pkg/helpers/fingerprint/fingerprint.go#L61) are taken into account ). However, without the change the GUID could change depending on the fullHostname and therefore depending on the services running in the cluster. 
Notice that we …
> fix(hostname): overriding fullhostname

- Makefile
- src/controlplane/controlplane_test.go
- src/kubelet/kubelet_test.go
- src/metric/definition.go
Skipping e2e because could fail as it is not in the entity definitions yet.
Metrics added to the table of the metrics we have to add to the spec files: #455
> Add k8s v1.23 & v1.24 new metrics

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/templates/kubelet/integrations-configmap.yaml
- charts/newrelic-infrastructure/tests/configmap_integrations_test.yaml
I checked and that tpl was there since the very first implementation of v3, not really sure why we needed double templating (in that case we need to find a different solution). 
I am not aware of an use case based on that.
Fix https://github.com/newrelic/nri-kubernetes/issues/500
> fix(chart): removing doublerender to support old passthorugh notation

- src/controlplane/controlplane_test.go
- src/kubelet/kubelet_test.go
- src/metric/definition.go
- src/prometheus/definition.go
- src/prometheus/definition_test.go
This PR adds the capability to filter k8s metrics by label values.
This will avoid errors like this one  https://github.com/newrelic/nri-kubernetes/issues/397 we faced in the past.
> Filter k8s metrics by label values

- .github/workflows/e2e.yaml
- e2e/1_22-exceptions.yml
- e2e/1_23-exceptions.yml
- e2e/1_24-exceptions.yml
- e2e/README.md
- e2e/k8s.yml
- e2e/test-specs.yml
Closes #438 and Closes #448 but... since the metrics added on 1.23 and 1.24 are not yet correctly shimmed to DM I added to the exceptions. 
Exceptions metrics files has been added depending on the k8s version since some metrics were added and removed on different versions.
> test: Add v1.23 and v1.24 e2e tests.

- src/controlplane/client/authenticator/authenticator.go
- src/controlplane/client/authenticator/authenticator_mtls_test.go
- src/controlplane/client/authenticator/authenticator_test.go
- src/controlplane/client/authenticator/test_data/token
- src/kubelet/client/client_test.go
- src/kubelet/client/connector.go
- src/kubelet/client/test_data/token
Fix https://github.com/newrelic/nri-kubernetes/issues/511
Changing 
- setting `NewBearerAuthWithRefreshRoundTripper` instead of `NewBearerAuthRoundTripper` to fix kubelet
and 
- setting `transportConfig.BearerTokenFile` instead of  `transportConfig.BearerToken` to fix controlPlane
- using `require` to avoid null pointer exception if creation of some resources fails and also if they are the only condition tested in a test-case (basically to remove an import)
> fix(kubeletConnection): leverage token refresh

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/templates/_helpers_compatibility.tpl
This is the only chart remaining to fix the issue newrelic/helm-charts#858
Go to the issues linked for having all the context.
TL;DR: `mergeOverwrite` does not only return the resulting dict but also modifies the first parameter so we have to `deepCopy`  it to not change values for the rest of the helpers/templates.
Fixes newrelic/helm-charts#858
> [helm chart] `deepCopy` values when we are going to do a `mergeOverwrite`

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/templates/_helpers_compatibility.tpl
- charts/newrelic-infrastructure/templates/controlplane/_naming.tpl
- charts/newrelic-infrastructure/templates/controlplane/clusterrolebinding.yaml
- charts/newrelic-infrastructure/templates/controlplane/daemonset.yaml
- charts/newrelic-infrastructure/templates/controlplane/rolebinding.yaml
- charts/newrelic-infrastructure/templates/controlplane/serviceaccount.yaml
- charts/newrelic-infrastructure/tests/controlplane_rbac_test.yaml
- charts/newrelic-infrastructure/tests/controlplane_serviceAccount_test.yaml
- charts/newrelic-infrastructure/tests/interval_override_test.yaml
There is an issue open by GTS saying that not all the charts honor the flag `.global.serviceAccount.create` and `.global.serviceAccount.name`: newrelic/helm-charts#875
There is not also the issue that they are not honored by the deployments but also by the jobs that create and patch webhook certificates.
Fixes #514
> [helm chart] Patch job should also honor the global service account flag

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/tests/serviceaccount_create_test.yaml
- charts/newrelic-infrastructure/values.yaml
Having the `create: true` on the default values of the chart was preventing the global values to overwrite this config ([issue](https://github.com/newrelic/helm-charts/issues/875))
This PR removes the default values so the `global.serviceAccount` are honored.
> fix: remove fixed serviceAccount.create of values

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
Bump chart images. The important one is the `infrastructure-bundle` that comes with the fix for the `Heartbeat context cancelation`.
> Bump chart images

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
@bpschmitt originally posted in PR #553 this:
> Disables the flex-based `pixieHealthCheck` events by default.  There is an error in the flex script syntax that needs to be debugged and it's currently creating noise.  Will re-enable once I get time to fix it.
He opened this PR while GitHub was having an incident and seems to have cached a glitched version of the code/action because it is failing with an action that has has no changes since 8 months ago.
We are recreating manually the PR to test it again.
> set pixie check to false

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
We still need to update `newrelic/infrastructure-bundle` when [this PR](https://github.com/newrelic/infrastructure-bundle/pull/241) is merged.
> chore: bump chart version and dependencies

- src/definition/guessfunc.go
- src/definition/guessfunc_test.go
- src/definition/populate.go
- src/definition/populate_test.go
- src/metric/definition.go
- src/metric/definition_test.go
The signature could be reduced, but I would even get rid of the whole function if possible
> fix(signature): extra parameters were unused

- .github/workflows/e2e.yaml
- e2e/1_25-exceptions.yml
This PR updates the e2e testing to support K8s v1.25 by doing the following:
- Update `e2e.yaml` to include new K8s version
- Add exceptions file for v1.25 (using same exceptions as v1.24).
> Update e2e testing to support k8s v1.25

- .github/workflows/nightlyAndMainImage.yml
- .github/workflows/release-integration.yml
- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
Ping new version of infra bundle that solves some vulns; you can follow the conversation [here](https://newrelic.slack.com/archives/CP2EWSX7C/p1673970141838969). Leveraged and updated some other dependencies.
> Bump chart version and dependencies

- README.md
- charts/internal/e2e-resources/templates/cronjob.yml
This PR fixes the local dev environment (`make local-env-start`) , which was broken in #608. In that PR, I added the `apiVersion` templating to the new `CronJob` resource in order to fix an E2E build error, but I forgot to go back and test the local dev environment. 
**Current broken behavior**
- When running the local dev environment, the [e2e-resource workloads](https://github.com/newrelic/nri-kubernetes/tree/main/charts/internal/e2e-resources/templates) are not deployed.  
- The local dev environment uses Tilt which uses `helm template` to deploy the e2e-resource workloads: https://github.com/newrelic/nri-kubernetes/blob/main/Tiltfile#L54
- Helm template doesn't have access to `.Capabilities.APIVersions` (helm/helm#3377) and I didn't have an else statement to provide a default …
> Fix local dev environment.

- .github/workflows/e2e.yaml
- Makefile
- charts/internal/e2e-resources/Chart.yaml
- e2e/README.md
- e2e/test-specs.yml
- internal/testutil/datagen/datagen.sh
In order to fix KSM and k8s versions incompatibility in e2e tests, the change in this [PR](https://github.com/newrelic/nri-kubernetes/pull/595) disabled KSM auto installation. As a result, CI scripts that ran e2e tests had to detect which k8s version  running and manually install the correct KSM version. Even though this pattern made all e2e tests to pass, but it affect the `datagen.sh` script to set up correct environment. This PR is to fix this issue.
This PR put back KSM auto installation feature, but still allow correct KSM version installation by adding back the KSM dependency in the charts/internal/e2e-resources/Chart.yaml file and making use of `--set kube-state-metrics.image.tag` in helm command.
> Fix datagen.sh

- e2e/1_23-exceptions.yml
- e2e/1_24-exceptions.yml
- e2e/1_25-exceptions.yml
- e2e/1_26-exceptions.yml
I can't find the specific PR that these were added in, but generally the E2E exception files are used so that E2E testing will pass for `nri-kubernetes` agent changes before the backend changes that transform these metrics to dimensional metrics have landed. These metrics have now been transformed (as seen in the `e2e/k8s.yml` file), so they can now be removed from the exception file.
> [Cleanup] Remove E2E metric exceptions

- .github/workflows/e2e.yaml
- .github/workflows/push_pr.yaml
The `set-output` command is deprecated and will be fully disabled this May: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
This will clean up a lot of warnings when these workflows run.
> Update deprecated GitHub set-state action

- Dockerfile
Dependabot PRs don't work with E2E testing. Recreating https://github.com/newrelic/nri-kubernetes/pull/628 so that we can run E2E tests.
> chore(deps): bump alpine from 3.17.1 to 3.17.2

- charts/internal/e2e-resources/Chart.yaml
- charts/internal/e2e-resources/README.md
- charts/internal/e2e-resources/templates/cronjob.yml
- charts/internal/e2e-resources/templates/job-fails.yaml
- charts/internal/e2e-resources/values.yaml
The Kubernetes team is working on adding new metrics for all Kubernetes workloads, including `Job`. This PR adds a failing `Job` workload that will be used in the local dev environment.
- Run local dev environment: make local-env-start
- Observe failed jobs
> Add failed job to testing resources.

- charts/internal/e2e-resources/Chart.yaml
- charts/internal/e2e-resources/README.md
- charts/internal/e2e-resources/values.yaml
The Kubernetes team is working on adding new metrics for all Kubernetes workloads, including `PesisitentVolumeClaim` and `PersistentVolume`. This PR adds a enables both workloads by default for the local dev environment and E2E testing. 
- Run local dev environment: make local-env-start
- Observe that `PV` and `PVC` workloads exist
> Enable PV and PVC by default in testing resources.

- charts/newrelic-infrastructure/Chart.yaml
- charts/newrelic-infrastructure/values.yaml
- cmd/nri-kubernetes/main.go
- internal/config/config.go
- src/kubelet/scraper.go
This PR addresses the issue when Kubelet becomes temporarily unavailable, no Kubelet metrics are populated, and the error "kubelet data was not populated after trying all endpoints" from Kubelet scraper is returned to main.  
The current behavior of K8s agent main is that if any (ksm, kubelet, controlplane) scrapers returns any error, the K8s agent will Immediately fail and exit with code 5.
Instead of exiting immediately when kubelet is not reachable, we can set a ScraperMaxReruns (e.g., 4 times) at the scraper level. This will improve customer experience when kubelet is temporarily not reachable.
> Rerun Kubelet Scraper When Data is Populated

- .github/workflows/nightlyAndMainImage.yml
- .github/workflows/release-integration.yml
- .github/workflows/security.yaml
Skipping E2E testing since this PR only changes the github workflows related to Trivy security scanning.
> chore(deps): bump aquasecurity/trivy-action from 0.8.0 to 0.9.1

- .github/workflows/release-chart.yml
Skipping E2E testing since this change only affects the github workflows. 
This change will get tested when we release a chart later today / early tomorrow am.
> Bump helm/chart-releaser-action from 1.3.0 to 1.5.0

- charts/internal/e2e-resources/templates/cronjob.yml
- charts/internal/e2e-resources/templates/job-fails.yaml
- internal/testutil/datagen/README.md
- internal/testutil/datagen/datagen.sh
`datagen.sh` is a tool to scrape static test data from a live cluster, and this data can then be used for integration tests. While useful, the tool is difficult to use and prone to error.
This PR addresses several of the shortcomings of the tool to make it easier to use for developers:
1. Automates the mapping of the cluster's Kubernetes version to the correct KSM version to use
2. Waits for new entities (job, cronjob) to settle before scraping test data
3. Avoids common human errors by automating the process
4. Makes workflow more resilient by testing for resource availability before starting the scrape process
None, this is a standalone PR.
> Improvements on `datagen.sh`

- src/controlplane/scraper.go
Several PRs are failling due to a misspelling in the code:
https://github.com/newrelic/nri-kubernetes/actions/runs/4380154432/jobs/7666903517
> Fix mispelling that causes Codespell test to fail

- .github/workflows/release-chart.yml
- In a previous PR, we disabled the Helm lint check which requires a version bump for any changes to chart details (https://github.com/newrelic/nri-kubernetes/pull/665)
- Since the Helm chart releaser triggers on every push to main, we need this flag to prevent the releaser from trying to overwrite an existing release and failing.
> Tell chart releaser to skip existing charts

- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/values.yaml
- internal/config/config.go
- src/kubelet/scraper.go
Adjust the relative reference of ScraperMaxReruns in order to make it explicitly clearer. This change is related to https://github.com/newrelic/nri-kubernetes/pull/633
- Change the way the parameter is referred in the code in order to make more explicit
- Add a default value in the config.go explicitly
- Change the default value of ScraperMaxReruns placement in the values.yaml
- Update readme
In my values-local.yaml, I make the following changes
```
cluster: minikube
global:
licenseKey: <my staging license key>
nrStaging: true
kubelet:
scraperMaxReruns: 4
```
The e2e tests succeeded means all the agents works as expected and can send data to NR backend.
Locally, I run `make local-env-start` and check the deployed agent status as follows
```
xqi@TFXCKKXMP9 nri-kubernetes % k get po | grep …
```
> Add Default Scraper Max Rerun

- Tiltfile
- charts/internal/e2e-resources/templates/namespace.yaml
When running the local dev environment, the local testing resources get deployed to the `default` namespace. This makes cleaning up the cluster a bit difficult. 
- Change the local dev environment to deploy the testing + agent resources to the `nri-k8s-dev` namespace. 
- Spin up local dev environment (`make local-dev-env`) and check that the testing resources deploy to the `nri-k8s-dev` namespace and that the cluster shows up in the New Relic UI.
> Deploy e2e testing resources to a specific namespace

- e2e/k8s.yml
- src/metric/definition.go
The Kubernetes team is updating metrics for all supported workloads and services. Specifically, [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) has upgraded several metrics and services from `experimental` to `stable`.
This PR makes changes to the agent to start scraping the following metrics:
For [Enpoint](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/endpoint-metrics.md#endpoint-metrics) services:
`kube_endpoint_info`
For [DaemonSet](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/daemonset-metrics.md#daemonset-metrics) workloads:
`kube_daemonset_status_observed_generation`
For [Deployment](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/deployment-metrics.md#deployment-metrics) workloads: …
> Add KSM metrics promoted to stable category

- .github/workflows/nightlyAndMainImage.yml
- .github/workflows/release-integration.yml
Recreates https://github.com/newrelic/nri-kubernetes/pull/652 since dependabot PRs don't work with E2E testing.
> chore(deps): bump docker/setup-qemu-action from 1 to 2

- .github/workflows/e2e.yaml
- .github/workflows/push_pr.yaml
Recreates https://github.com/newrelic/nri-kubernetes/pull/653 because dependabot PRs don't work with E2E testing.
> chore(deps): bump manusa/actions-setup-minikube from 2.4.3 to 2.7.2

- charts/newrelic-infrastructure/values.yaml
There's a new release out https://github.com/newrelic/infrastructure-bundle/releases/tag/3.1.1
> chore(deps) bump newrelic/infrastructure-bundle from 2.8.38 to 3.1.3

- .github/workflows/e2e.yaml
- .github/workflows/nightlyAndMainImage.yml
- .github/workflows/push_pr.yaml
- .github/workflows/release-integration.yml
Recreates #672 because dependabot PRs don't work with E2E testing.
> chore(deps): bump actions/setup-go from 3 to 4

- charts/internal/e2e-resources/templates/hpa.yaml
k8s.gcr.io image registry will be redirected to registry.k8s.io on Monday March 20th.
All images available in k8s.gcr.io are available at registry.k8s.io.
See https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
> Update Kubernetes image registry

- src/integration/prober/prober.go
The current K8s integration probes infra agent during the pod starts. The error message needs to be improved for debugging purpose.
I only made a small change to the existing debugging messages
No tests need to be done
> Improve Infra Agent Probing Messages

- go.mod
- go.sum
> chore(deps): bump google.golang.org/protobuf from 1.29.1 to 1.30.0

- .github/workflows/e2e.yaml
- e2e/1_16-exceptions.yml
- e2e/1_22-exceptions.yml
- e2e/k8s.yml
- src/ksm/ksm_test.go
- src/metric/definition.go
We are ready to release Kubernetes `CronJob` and `Job` metrics. 
This PR adds the following two commits using `git cherry-pick`:
- Add CronJob KSM metrics. (#609)
- Add Job KSM metrics. (#626)
Both commits were previously reverted in https://github.com/newrelic/nri-kubernetes/pull/688. However, PR #688 reverted other commits (including #629 and #639) so I couldn't revert #688 directly since we only want to release 2 of those commits now.
> Add CronJob and Job KSM metrics

- .github/workflows/push_pr.yaml
Fixes https://github.com/newrelic/nri-kubernetes/actions/runs/4734869907/jobs/8404363346?pr=721.
Now that https://github.com/helm-unittest/helm-unittest/pull/114 has made Helm3 support the default, we no longer need to specify Helm3.
> Fix push_pr workflow

- e2e/k8s.yml
- src/ksm/ksm_test.go
- src/metric/definition.go
The Kubernetes team is updating metrics for all supported workloads and services. Specifically, [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) has upgraded several metrics and services from `experimental` to `stable`.
We noted in the Kubernetes repository that there are [only three valid conditions of a deployment](https://github.com/kubernetes/kubernetes/blob/3615291/pkg/apis/apps/types.go#L460-L473):
- `Available`
- `Progressing`
- `ReplicaFailure`
While they are [briefly mentioned in the documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/), there is no statement indicating they are the only valid conditions.
This PR makes changes to the agent to start scraping the attribute `ReplicaFailure` from [KSM's metric …
> Adding new attribute `ReplicaFailure` to deployment workload

- .github/workflows/nightlyAndMainImage.yml
- .github/workflows/release-integration.yml
- .github/workflows/security.yaml
Recreating https://github.com/newrelic/nri-kubernetes/pull/723 because dependabot PRs don't work with E2E testing.
> chore(deps): bump aquasecurity/trivy-action from 0.9.2 to 0.10.0

- src/ksm/ksm_test.go
- src/kubelet/kubelet_test.go
PR #733 updated the Kubelet tests to exclude all optional metrics.
This PR updates the Kubelet tests to more specifically exclude just the changes added in #733.
> Update kubelet static testing exclusions.

- src/prometheus/query.go
- src/prometheus/query_test.go
Using prom2Json results in the implicit loss of all metric families when any error is encountered while reading the prometheus exposition format. 
This change is a sort of POC to show that by directly using the parser provided by the prometheus library, we the callers can choose what to do with some of the seen metrics before an error was encountered while parsing. 
None of the functionality of the scrapers were changed and they remain semantically the same. 
A test was added to show how `parseResponse` preserves metric families that are seen even when parsing errors are encountered. The behaviour is to only keep the metrics seen up until the time of failure
I have successfully run the e2e tests locally and through the github actions here. 
Added new unit/feature tests and locally, …
> chore(deps): Directly Use Prometheus Parser - remove prom2json dep 

- .github/workflows/changelog.yml
- CHANGELOG.md
- CONTRIBUTING.md
Adding a changelog action that valids if a PR updates a changelog by using the `newrelic/release-toolkit/validate-markdown@v1`.
Relates to this PR: https://github.com/newrelic/nri-kubernetes/pull/836
> chore: Add CHANGELOG github workflow

- .github/renovate.json5
- .github/workflows/changelog.yml
- CONTRIBUTING.md
We need to skip running the changelog workflow for dependency bump prs and for any prs that don't need a changelog like updating the codeowners files for example.
- Updated changelog workflow to not run if a pr has a label of `dependencies` or `Skip Changelog`. 
- Updated renovatebot to add a label of "dependencies". Note: dependabot already adds this label.
Not applicable in this PR
> chore: Add labels to changelog workflow and renovatebot

- CHANGELOG.md
- src/metric/definition.go
In #867 we used an experimental metric to generate the HPA ID and type. This PR uses instead a stable metric.
Scraping stable metrics is a better approach than using experimental metrics that can change without notice.
> fix: Use a stable metric instead of an experimental one

- .github/workflows/e2e.yaml
- .github/workflows/push_pr.yaml
Updating minikube version so Helm chart linting works for Kubernetes v 1.27
> ci: Update minikube version

- e2e/1_24-exceptions.yml
- e2e/1_25-exceptions.yml
- e2e/1_26-exceptions.yml
- e2e/1_27-exceptions.yml
- e2e/1_28-exceptions.yml
- e2e/test-specs.yml
Deprecated metrics should go into the common exceptions, no need to duplicate them in each exception file specific to a given Kubernetes version
> feat: Update E2E test exceptions

- CHANGELOG.md
- e2e/test-specs.yml
Add e2e nrql tests for pod dashboard for container pending.
> Add Failed Pod - Container Pending Test

- CHANGELOG.md
- charts/newrelic-infrastructure/templates/controlplane/daemonset.yaml
- charts/newrelic-infrastructure/templates/ksm/deployment.yaml
- charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml
- charts/newrelic-infrastructure/tests/nodeSelectors_test.yaml
> feat: add linux node selector

- CHANGELOG.md
- charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml
Infrastructure Agent captures Storage Samples of underlying nodes based on the mounted file system. Whenever a new pvc is mounted on the host, this mount needs to be propagated (`rslave`)to the mounted filesystem in the agent container. 
By default k8s uses `none` as mount propagation, and according to [k8s docs](https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation) depends on the CRI which propagation is used `rprivate` or in some cases like docker `rslave`. 
This PR configures the host file system volume to be mounted with `rslave` independently of the CRI. This fixes some miss behaving storage metrics samples where the device disk space of a newly mounted device has the value of the primary host storage ( and the issue was fixed upon Pod recreation)
> fix: pin mountPropagation of host fs in privileged mode (NR-274598)

- .github/ISSUE_TEMPLATE/config.yml
- CHANGELOG.md
- charts/newrelic-infrastructure/README.md
- charts/newrelic-infrastructure/README.md.gotmpl
- charts/newrelic-infrastructure/tests/affinity_controlPlane_test.yaml
- charts/newrelic-infrastructure/values.yaml
- src/kubelet/grouper/group_test.go
- src/kubelet/metric/testdata/kubelet_group_expected.go
`node-role.kubernetes.io/master` was [removed in Kube 1.24](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes) so we shouldn't need to select for it.  `node-role.kubernetes.io/control-plane` was added in Kube 1.20 as the replacement and should be used going forward.  [A deprecation warning](https://github.com/kubernetes/kubernetes/blob/81ce66f059ec9c07cccf4069c8913e31959dea78/pkg/api/node/util.go#L36) was added in Kube 1.31 which causes [open-install-library](https://github.com/newrelic/open-install-library) to fail install if we include that label in the selectors.
This is a breaking change for Kube less than 1.20, which we do not officially support.
> fix: The master node-role was removed in Kube 1.24

- CHANGELOG.md
- src/definition/populate.go
- src/definition/populate_test.go
Add K8s Integration Version to Inventory
[NR-332888](https://new-relic.atlassian.net/browse/NR-332888)
[NR-332888]: https://new-relic.atlassian.net/browse/NR-332888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add Integration Version to Inventory Payload

- .github/workflows/windows-infra-agent.yml
This updates the GHA that builds the Windows nri-kubernetes & agent images to use the new agent repo.
> chore: update target repo for windows-based infra agent

- .github/workflows/build-win-infra-agent.yml
- .github/workflows/build-windows-integration-test.yml
- .github/workflows/changelog.yml
- .github/workflows/e2e.yaml
- .github/workflows/nightlyAndMainImage.yml
- .github/workflows/push_pr.yaml
- .github/workflows/release-e2e-resources.yaml
- .github/workflows/repolinter.yml
- .github/workflows/trigger_release.yml
- to clean up all the new Medium security code scan alerts we were getting and reduce noise
> add permissions to gha to remove medium security alerts

- e2e/test-specs-windows.yml
- e2e tests were failing because an old node's data was still in NR Platform and the facet query count was wrong.
> add timeframe for windows e2e queries

- .github/workflows/test-windows-e2e.yml
- e2e/e2e-values-windows-template.yml
- e2e/test-specs-windows.yml
- making sure the scenario tag for tests on cluster v1.29 (or oldest) and v1.32 (newest) cluster versions are different so the E2E test queries don't get confused
- decrease sleep time for test-spec-windows
-
> chore: Update e2e windows scenario tag
