src/controlplane/components.go, src/controlplane/components_test.go
=> fix: custom endpoint set up logic for components

.github/workflows/test.yaml, CHANGELOG.md, Dockerfile
Bump the infra bundle with to last version.
=> Updated infrastructure-bundle to v1.6.0

.github/workflows/release.yml
=> Release using github actions

.github/workflows/release.yml
=> ci: check deployment ymls point to the released version

README.md
Improving documentation @bpschmitt
=> feat(documentation): adding info regarding image released

deploy/newrelic-infra-unprivileged.yaml, deploy/newrelic-infra.yaml
Following the change in the helm chart we need to update as well the static manifests
=> fix(permissions): dropping some permissions and deleted old manifest

Dockerfile, deploy/newrelic-infra-unprivileged.yaml, deploy/newrelic-infra.yaml
Updating bundle to 2.5.0 -> https://hub.docker.com/layers/newrelic/infrastructure-bundle/2.5.0/images/sha256-2a9d0241120f9b3a7fd438575a793463676edfebf649aca5b48ba405f8938381?context=explore
=> Updating bundle versions and manifest

CHANGELOG.md, deploy/newrelic-infra-unprivileged.yaml, deploy/newrelic-infra.yaml, src/kubernetes.go
- Bump integration version so it appears updated in the samples.
=> Bump integration version

.github/workflows/nightly.yml
It also still depends on https://github.com/newrelic/infrastructure-bundle/pull/67
Signed-off-by: Mateusz Gozdek <mgozdek@microsoft.com>
=> .github/workflows/nightly.yml: fix used base image

.github/workflows/release.yml, Makefile, src/kubernetes.go
SHA1 of HEAD will also be picked up automatically by Makefile
Fixes #131
=> build: pick up integration version from TAG env var

e2e/README.md, e2e/charts/newrelic-infrastructure-k8s-e2e/values.yaml, e2e/schema/node-no-network.json, e2e/schema/node.json, src/metric/definition.go
=> feat: add unschedulable node metric

cmd/kubernetes-discovery/main.go, e2e/scenario/scenario.go, src/client/client.go, src/client/client_mock.go, src/ksm/client/cached_test.go, src/ksm/client/discovery.go, src/ksm/client/discovery_test.go, src/ksm/client/distributed_pod_label_discovery.go, src/ksm/client/distributed_pod_label_discovery_test.go, src/ksm/client/pod_label_discovery.go, src/ksm/client/pod_label_discovery_test.go, src/kubernetes.go
Partially addresses the review comments from #165.
Draft, as I'm still not 100% sure about exposing `LookupSRV` field.
=> Refactor src/client and src/ksm/client a bit

src/metric/definition.go
=> metric: add nodeName attribute to node specs

.github/workflows/e2e.yaml, .github/workflows/push_pr.yaml, .github/workflows/release.yml, CHANGELOG.md, Dockerfile, README.md, e2e/charts/newrelic-infrastructure-k8s-e2e/templates/daemonset.yaml, e2e/cmd/e2e.go, e2e/scenario/scenario.go, src/prometheus/definition.go, src/prometheus/metric.go
=> e2e: improvements

cmd/kubernetes-discovery/main.go, e2e/cmd/e2e.go, e2e/scenario/scenario.go, src/client/client.go, src/client/client_mock.go, src/ksm/client/discovery.go, src/ksm/client/discovery_test.go, src/ksm/client/distributed_pod_label_discovery.go, src/ksm/client/pod_label_discovery.go, src/ksm/group.go, src/kubernetes.go
Closes #105
Draft as tests are missing.
=> Add KSM namespace selector flag support

CHANGELOG.md, Dockerfile, deploy/newrelic-infra-unprivileged.yaml, deploy/newrelic-infra.yaml
Bumps bundle and creates changelog
=> release v2.8.0

.github/workflows/push_pr.yaml, src/apiserver/cache_client.go, src/apiserver/client_test.go, src/client/cached.go, src/client/cached_test.go, src/client/discovery_mock.go, src/ksm/client/cached.go, src/ksm/client/cached_test.go, src/kubelet/client/cached.go, src/kubelet/client/cached_test.go, src/kubernetes.go, src/storage/memory.go, src/storage/memory_test.go
See commit messages for more details.
Closes #177
=> Add TTL jitter support to cache expiry

CHANGELOG.md, Dockerfile, deploy/newrelic-infra-unprivileged.yaml, deploy/newrelic-infra.yaml
Out-of-tree release cherry-picking 6e8b3376c42a03f5b3b79ffb0f785175d091fc78
=> v2: Release 2.8.2

.github/workflows/e2e.yaml, .github/workflows/nightly.yml, .github/workflows/push_pr.yaml, .github/workflows/release.yml
=> ci: implement caching, allow to skip e2e tests

e2e/charts/newrelic-infrastructure/templates/clusterrole.yaml, internal/discovery/secret_lister.go, internal/discovery/secret_lister_test.go
Adding lister for secrets returning directly the namespaced function.
=> feat(ETCDsecrets): added secretNamespaceLister

.github/workflows/release.yml
=> Remove Test push new image

.gitignore, cmd/nri-kubernetes/main.go, internal/config/config.go
=> Fix config file location

.github/workflows/nightly.yml
Nightly images were still pointing to old repo
=> Fix: Nightly images

cmd/nri-kubernetes/main.go, internal/config/config.go, internal/config/testdata/config.yml, internal/config/testdata/config_with_unexpected_fields.yml, src/definition/populate.go, src/network/interfaces_default.go, src/sink/http.go, src/sink/http_test.go
=> Add backoff delay from pester to the agent forwarder

src/kubelet/client/client.go, src/kubelet/scraper.go
Fix https://github.com/newrelic/nri-kubernetes/issues/325
After checking memory leaks I noticed that kubelet fails from time to time due to kubelet not answering
=> feat(kubelet): adding pester as client wrapper

.github/workflows/e2e.yaml
=> e2e: also run tests with containerd

.github/workflows/nightlyAndMainImage.yml
Using bash if-else since github action is not supporting if-else statements.
=> feat(ci/cd): main build

CHANGELOG.md
Check it [here](https://github.com/newrelic/nri-kubernetes/blob/chore/changelog/CHANGELOG.md)
=> chore(changelog): update changelog for v3.2.0

README.md, charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/README.md.gotmpl, charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml, charts/newrelic-infrastructure/values.yaml
With the implementation of the common library, a couple of values changed and some features have been added.
We can also add more documentation to this chart.
There is a spurious change in the `templates/kubelet/daemonset.yaml` file. As I have to bump the version to change the documentation I am fixing also that bug that I found while I was doing the docs.
=> Update of the docs

src/kubelet/metric/resource.go, src/kubelet/metric/resource_test.go
=> fix: round up CPU allocatable and capacity metrics

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/ci/test-values.yaml, charts/newrelic-infrastructure/flex/nri-pixie-check.yaml, charts/newrelic-infrastructure/templates/NOTES.txt, charts/newrelic-infrastructure/templates/_helpers.tpl, charts/newrelic-infrastructure/templates/clusterrole.yaml, charts/newrelic-infrastructure/templates/clusterrolebinding.yaml, charts/newrelic-infrastructure/templates/configmap.yaml, charts/newrelic-infrastructure/templates/daemonset-windows.yaml, charts/newrelic-infrastructure/templates/daemonset.yaml, charts/newrelic-infrastructure/templates/podsecuritypolicy.yaml, charts/newrelic-infrastructure/templates/rolebinding.yaml, charts/newrelic-infrastructure/templates/secret.yaml, charts/newrelic-infrastructure/templates/serviceaccount.yaml, charts/newrelic-infrastructure/values.yaml
Not only I added the chart but also updated it to the latest version. Take a look at the commits :)
Do not merge until #414 is merged.
=> Add v2 chart

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/templates/ksm/scraper-configmap.yaml, charts/newrelic-infrastructure/tests/configmap_ksm_scraper_test.yaml, charts/newrelic-infrastructure/values.yaml
=> [chart] Document ksm defaults in the values

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/templates/controlplane/daemonset.yaml, charts/newrelic-infrastructure/templates/ksm/deployment.yaml, charts/newrelic-infrastructure/tests/controlplane_strategy_test.yaml, charts/newrelic-infrastructure/values.yaml
This is a rip-off of newrelic/helm-charts#697 made by @roobre that is in the helm-charts repo and I could not cherry-pick.
Solves #356
=> [chart] Add recreate strategy to deployments

Dockerfile
https://github.com/goodwithtech/dockle/blob/master/CHECKPOINT.md#cis-di-0009=
=> Dockerfile: use COPY instead of ADD

CHANGELOG.md
=> Update changelog to v3.3.0

src/ksm/scraper.go
=> Wrap noData error with filter specific message

CHANGELOG.md, src/definition/populate.go, src/definition/populate_test.go, src/ksm/ksm_test.go, src/ksm/scraper.go, src/metric/definition.go
=> Add nrFiltered attribute to namespaceSample when filtering by namespace

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/values.yaml
=> Bump infrastructure-bundle and integration to the last vesions

.gitignore, Makefile, README.md, Tiltfile, values-dev.yaml, values-local.yaml.sample
Adds a local dev environment using Tilt with hot reload.
=> Add Tilt environment 

CHANGELOG.md, charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/values.yaml
Closes https://github.com/newrelic/nri-kubernetes/issues/456.
=> Bump chart and images

Dockerfile, e2e/test-specs.yml
Closing https://github.com/newrelic/nri-kubernetes/pull/518
=> Bump alpine 3.16.1 and run ci/cd

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/tests/configmap_cp_scraper_test.yaml, charts/newrelic-infrastructure/values.yaml, src/controlplane/scraper.go, src/metric/definition.go
Adding new endpoints for openshift. Tested with openshift 4.10
=> feat(chart): adding new openshift endpoint

charts/newrelic-infrastructure/Chart.yaml
Updating chart with released image
=> chore(v2): chart update

e2e/README.md
Signed-off-by: paologallinaharbur <paologallina1992@gmail.com>
=> feat(readme): improving running e2e locally docs

e2e/README.md
=> Improve e2e readme

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md, charts/newrelic-infrastructure/templates/ksm/_host_network.tpl, charts/newrelic-infrastructure/templates/ksm/deployment.yaml, charts/newrelic-infrastructure/templates/kubelet/_host_network.tpl, charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml, charts/newrelic-infrastructure/tests/hostNetwork_test.yaml, charts/newrelic-infrastructure/values.yaml
A rebased version of the PR #592 made by @dpacheconr.
E2e tests are failing, we already saw that in other PRs of some people and it seems to be a glitch in the actions as they cache some runs or something out of our control. Recreating the PR always fix the issue.
This PR should pass the tests and fix the issue not only with the CI but the one of the PR from the contributor.
=> Fix host network

.github/workflows/nightlyAndMainImage.yml, .github/workflows/release-integration.yml, .github/workflows/repolinter.yml, .github/workflows/security.yaml
Recreating dependabot PRs https://github.com/newrelic/nri-kubernetes/pull/605 and https://github.com/newrelic/nri-kubernetes/pull/564 since they don't work with E2E testing.
=> chore(deps): update github workflow dependencies

Tiltfile
Make the alpine version in the Tiltfile consistent to the one in Dockerfile
=> Update Alpine Version in Tiltfile

charts/newrelic-infrastructure/values.yaml
This PR recreates #603 since E2E testing doesn't work from forks.
=> Fix matchExpressions value example

charts/internal/e2e-resources/README.md, charts/newrelic-infrastructure/README.md
=> Run helm-docs

.github/workflows/e2e.yaml, .github/workflows/nightlyAndMainImage.yml, .github/workflows/push_pr.yaml, .github/workflows/release-chart.yml, .github/workflows/release-integration.yml, .github/workflows/repolinter.yml, .github/workflows/security.yaml
Recreates #671 because dependabot PRs don't work with E2E testing.
=> chore(deps): bump actions/checkout from 2 to 3

Dockerfile, Tiltfile
=> chore(deps): bump alpine from 3.17.2 to 3.17.3

.github/workflows/push_pr.yaml
=> chore(deps): bump helm/chart-testing-action from 2.3.1 to 2.4.0

charts/newrelic-infrastructure/Chart.yaml
=> Bump app and chart version

charts/internal/e2e-resources/templates/cronjob.yml
Adding CPU/memory limits so CPU/memory utilization panes show data
=> CronJob chart improvement

.github/workflows/e2e.yaml, .github/workflows/nightlyAndMainImage.yml, .github/workflows/push_pr.yaml, .github/workflows/release-integration.yml
Thanks to @vihangm for finding this fix. :)
=> Remove manual go cache since setup-go/v4 automatically caches

charts/internal/e2e-resources/Chart.yaml, charts/internal/e2e-resources/README.md, charts/internal/e2e-resources/templates/deployment.yaml
Add new specs to allow for testing of new KSM metrics that are now supported
=> Improve testing for deployment object

.github/workflows/push_pr.yaml, charts/newrelic-infrastructure/tests/annotations_test.yaml, charts/newrelic-infrastructure/tests/configmap_cp_agent_test.yaml, charts/newrelic-infrastructure/tests/configmap_cp_scraper_test.yaml, charts/newrelic-infrastructure/tests/configmap_integrations_test.yaml, charts/newrelic-infrastructure/tests/configmap_ksm_agent_test.yaml, charts/newrelic-infrastructure/tests/configmap_ksm_scraper_test.yaml, charts/newrelic-infrastructure/tests/configmap_kubelet_agent_test.yaml, charts/newrelic-infrastructure/tests/controlplane_rbac_test.yaml, charts/newrelic-infrastructure/tests/initContainers_test.yaml, charts/newrelic-infrastructure/tests/interval_override_test.yaml, charts/newrelic-infrastructure/tests/serviceaccount_create_test.yaml
Fixes https://github.com/newrelic/nri-kubernetes/actions/runs/4774812363/jobs/8488726835?pr=721.
=> Fix Helm unittests

CHANGELOG.md, Dockerfile, go.mod, go.sum
=> [V2 branch] Update CHANGELOG.md and Dockerfile

charts/newrelic-infrastructure/Chart.yaml
=> Bump chart

charts/newrelic-infrastructure/templates/kubelet/daemonset.yaml
https://issues.newrelic.com/browse/NEWRELIC-5968
=> NEWRELIC-5968 Mount containerd socket

go.mod, go.sum, src/prometheus/definition_test.go
Recreating on PR #767
On [release 0.4.0](https://github.com/prometheus/client_model/releases/tag/v0.4.0) there was an [update to proto tools](https://github.com/prometheus/client_model/pull/64)
=> Update Prometheus dependencies

.github/workflows/changelog.yml, CHANGELOG.md
Update changelog workflow to:
- fail if the changelog file is not modified
- run changelog on prs on any branch
=> Chore: Update changelog workflow

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Add a template for pull requests to standardize them.
=> chore: Add Pull Request Template

charts/newrelic-infrastructure/Chart.yaml
Please include a summary of the change in your pr and what it's fixing. 
=> Bump versions

.github/workflows/push_pr.yaml, CHANGELOG.md
Companion to #867 
Updating the Kubernetes versions used while linting the Helm charts
=> feat(tests):Update Helm chart lint job

CHANGELOG.md
Update changelog to prepare for release 3.17.0
- Update changelog file
NA
NA
=> Update changelog for release 3.17.0

CHANGELOG.md, charts/newrelic-infrastructure/Chart.yaml
Bump app Version to 3.17.0 and chart to 3.22.0
Update chart file. 
=> chore: Bump appVersion to 3.17.0 and chart to 3.22.0

.github/renovate.json5
Fix KSM version to what has been tested for supported versions.
=> feat(ksm): Disable renovate from trying to update KSM dependency

.gitignore, Dockerfile
Address CVEs in Dockerfile base image
=> fix: Address CVEs in Dockerfile base image

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md
Please include a summary of the change in your pr and what it's fixing. 
=> [V2] Bump versions

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md
Please include a summary of the change in your pr and what it's fixing. 
=> ci: Update pull request template

.github/workflows/changelog.yml
=> ci: Update `changelog` workflow to use reusable one

.github/renovate.json5, .github/workflows/nightlyAndMainImage.yml, .github/workflows/push_pr.yaml, .github/workflows/release-chart.yml, .github/workflows/release-integration.yml, .github/workflows/security.yaml, .github/workflows/trigger_prerelease.yml, .gitignore, CHANGELOG.md, Makefile
Enable the automatic release of images and charts
=> feat: Enable automatic release

.github/renovate.json5
Update renovate to auto bump minikube version in any workflows files
=> chore: Update renovate file

.github/workflows/e2e.yaml
Minikube version was downgraded to workflow testing. Reverting that now.
=> fix: Update e2e.yaml

.github/renovate.json5, .github/workflows/e2e.yaml, .github/workflows/push_pr.yaml, CHANGELOG.md
Fixes issues with renovate configuration when trying to update `Minikube`
=> fix: Fix renovate configuration

.github/renovate.json5, .github/workflows/e2e.yaml
- Replace `matchRepositories` field for `matchDepNames`
- Run 'E2E over minikube' workflow so Renovate can automerge
=> fix: Fix renovate group

.github/workflows/push_pr.yaml
Disabling [semgrep action that has been deprecated](https://github.com/returntocorp/semgrep-action)
=> fix: Disable semgrep action that has been deprecated

CHANGELOG.md, e2e/README.md, e2e/test-specs.yml
Add e2e nrql tests for cronjob dashboard.
=> Add CronJob dashboard tests.

CHANGELOG.md, e2e/test-specs.yml
Add e2e nrql tests for pod dashboard for container creating.
=> Add Failed Pod - Container Creating Test

CHANGELOG.md, e2e/README.md, e2e/e2e-tests.sh
Simplify workflow to run local E2E tests
=> Automate local E2E test runs

CHANGELOG.md, e2e/k8s.yml, e2e/test-specs.yml
In order to have the latest metric definitions, we need to copy the [kubernetes.yml from infra-integration-specs](https://source.datanerd.us/infrastructure/infra-integration-specs/blob/master/specs/kubernetes.yml)
=> feat: Update k8s.yml for E2E testing

.github/workflows/e2e.yaml
Update secrets to use K8s Agents E2E account
=> ci: Update secrets

.github/workflows/changelog.yml, .github/workflows/release-chart.yml, .github/workflows/release-integration.yml, .github/workflows/security.yaml, .github/workflows/trigger_prerelease.yml, CHANGELOG.md
Update reusable workflow dependency
=> feat: Update reusable workflow dependency

CHANGELOG.md
=> fix: Fix CHANGELOG.md

CHANGELOG.md, charts/newrelic-infrastructure/templates/clusterrole.yaml
Recreates #933 in order to be able to run tests (forks have security limitations that stop them from successfully running tests). Fixes #932
=> fix: Update clusterrole.yaml

.github/workflows/push_pr.yaml, CHANGELOG.md, Makefile, README.md
=> ci: add Codecov

.github/workflows/push_pr.yaml
=> chore: update codecov config

.github/workflows/release-chart.yml
=> [V2] chore: Update permission

.github/workflows/nightlyAndMainImage.yml, .github/workflows/release-integration.yml
=> chore: Update secrets

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md
- [ x] Security fix
- [ x] Documentation has been updated
=> [v2] version bump

.github/workflows/release-e2e-resources.yaml, CHANGELOG.md
Automatically release E2E resources chart so it can be easily reused
=> feat: Automatically release E2E resources chart

CHANGELOG.md, charts/internal/e2e-resources/Chart.yaml, charts/internal/e2e-resources/README.md, charts/internal/e2e-resources/templates/daemonset.yaml, charts/internal/e2e-resources/templates/deployment.yaml
=> feat: Update `e2e-resources` chart

CHANGELOG.md
I mistakenly formatted the changelog as if the code was released, but was actually supposed to follow this format: [release-toolkit](https://github.com/newrelic/release-toolkit/blob/main/README.md#validate-markdown)
=> fix: Changelog format was incorrect for PR 1114 and 1118

CHANGELOG.md, charts/internal/e2e-resources/Chart.yaml, charts/internal/e2e-resources/templates/_naming.tpl, charts/internal/e2e-resources/templates/windows-deployment.yaml
=> update windows e2e-resources with better tolerations and dns safe naming

charts/newrelic-infrastructure/values.yaml
=> add values windowsAgentTag

charts/newrelic-infrastructure/Chart.yaml, charts/newrelic-infrastructure/README.md
=> chore: update maintainers

CHANGELOG.md
=> update readme for bugfix for future dev

CHANGELOG.md, README.md, charts/newrelic-infrastructure/README.md.gotmpl, charts/newrelic-infrastructure/templates/NOTES.txt, charts/newrelic-infrastructure/values.yaml, windows/infrastructure-agent/README.md, windows/nri-kubernetes/README.md
Updates READMEs to indicate Windows support for nri-kubernetes integration 🎉
=> chore: update readmes for windows support

.github/workflows/e2e.yaml
=> add github token to prevent rate limit error

.github/workflows/build-win-infra-agent.yml
=> update runner for building windows infra agent

CHANGELOG.md, charts/internal/e2e-resources/Chart.yaml
- updating the chart version to encompass the new windows charts for e2e-resources (to be used in canaries)
=> feat: update e2e-resources chart version

CHANGELOG.md, e2e/test-specs-windows.yml, e2e/test-specs.yml
=> fix: change e2e test key from constant to label

CHANGELOG.md, e2e/test-specs-windows.yml, e2e/test-specs.yml
=> fix: update e2e tests to use the constant key again
